set_project("vision")
set_version("0.0.1")
add_rules("mode.debug", "mode.release")
set_languages("c++20")

rule("iceoryx_deps")
on_load(function(target)
	target:add("includedirs", "/usr/local/include/iceoryx/v")
	target:add("linkdirs", "/usr/local/lib")
	target:add("links", "iceoryx_posh", "iceoryx_hoofs", "iceoryx_platform")
end)
rule_end()

rule("openvino_deps")
on_load(function(target)
	target:add("includedirs", "/opt/intel/openvino_2024/runtime/include")
	target:add("linkdirs", "/opt/intel/openvino_2024/runtime/lib/intel64")
	target:add("links", "openvino")
end)
rule_end()

add_requires("opencv")
add_requires("eigen")
add_requires("yaml-cpp")
add_requires("magic_enum")
add_requires("nameof")
add_requires("g2o")
-- FIXME: g2o官方package的deps缺少fmt和spdlog导致链接不通过,
-- 得手动添加到～/.xmake/repositories/xmake-repo/packages/g/g2o/xmake.lua
add_requires("glfw")
add_requires("yaml_cpp_struct")
add_requires("fmt")

includes("src/third_party")
includes("src/msgs")
includes("src/tools")
includes("src/hardware")
includes("src/auto_aim")
includes("src/auto_buff")
includes("src/auto_ballistic")
