log_level: Info
debug_mode: true
show_image: false
publish_target_armors: false
tf_query_tolerance_ms: 200.0
camera_name: camera0
camera_frame_id: camera
odom_frame_id: odom
armors_sub_topic:
  service: armors
  instance: fake_ap
  event: data
armors_pub_topic:
  service: armors
  instance: tracker
  event: debug
serial_topic:
  service: aim_command
  instance: tracker
  event: data
target_conf:
  yaw_error_weight: 0.5
  match_error_scale: 0.5
  max_match_error: 0.8
  yaw_prior_noise: 0.05
  vyaw_prior_noise: 0.2 
  yaw_factor_noise: 0.02 
  vyaw_factor_noise: 0.01  #最好和dt一致
  translation_prior_noise:
    x: 0.05
    y: 0.05
    z: 0.05
  translation_factor_noise:
    x: 0.005
    y: 0.005
    z: 0.005
  velocity_prior_noise:
    x: 0.1
    y: 0.1
    z: 0.1
  velocity_factor_noise:
    x: 0.00001
    y: 0.00001
    z: 0.00001
  robot:
    lost_threshold_sec: 0.5
    ra_prior_noise: 0.005
    rb_prior_noise: 0.005
    dz_prior_noise: 0.002
    radius_min: 0.15
    radius_max: 0.5
    default_radius_a: 0.3
    default_radius_b: 0.2
    default_dz: 0.0
    ra_factor_noise:
      x: 0.001
      y: 0.001
      z: 0.001
      yaw: 0.001
    rbdz_factor_noise:
      x: 0.001
      y: 0.001
      z: 0.001
      yaw: 0.001
  outpost:
    lost_threshold_sec: 0.8
    default_radius: 0.26
    default_dz_a: 0.1
    default_dz_b: -0.1
planner_conf:
  dt_sec: 0.01
  fail_polling_interval_sec: 0.2
  trajectory_half_horizon: 50
  use_analytical_solution: true
  iterative_fly_time: true
  shoot_offset: 0
  yaw_offset: 0.0
  pitch_offset: 0.0
  fire_thresh: 0.005
  max_yaw_acc: 50.0
  Q_yaw: [9e6, 0]
  R_yaw: 1
  max_pitch_acc: 100.0
  Q_pitch: [9e6,0]
  R_pitch: 1
  max_bullet_speed: 25.0
  default_bullet_speed: 22.0
  min_bullet_speed: 10.0
  trajectory_conf:
    g: 9.8
    k: 0.103
    length_gimbal_to_barrel: 0.107
    time_step: 0.004
    max_pitch_iterate_count: 100
    min_pitch_error: 0.01
    gimbal_pitch_min_degree: 30.0
    gimbal_pitch_max_degree: -5.0
    half_search_range_degree: 5.0
    max_fly_time: 1.0
    max_aim_iterate_count: 100
    aim_ok_error_m: 0.01
