log_level: Debug
plot_info: true
always_on_task: true
show_image: false
tf_query_tolerance_ms: 200.0
camera_name: camera0
camera_frame_id: camera
odom_frame_id: odom
armors_sub_topic:
  service: armors
  instance: fake_ap
  event: data
serial_topic:
  service: aim_command
  instance: tracker
  event: data
robot_conf:
  max_match_distance_m: 0.4
  max_match_yaw_diff_degree: 15.0
  lost_threshold_sec: 0.5
  yaw_prior_noise: 9.0
  vyaw_prior_noise: 9.0
  translation_prior_noise:
    x: 0.1
    y: 0.1
    z: 0.1
  velocity_prior_noise:
    x: 0.5
    y: 0.5
    z: 0.5

  yaw_factor_noise: 0.1
  vyaw_factor_noise: 0.5
  translation_factor_noise:
    x: 0.03
    y: 0.03
    z: 0.03
  velocity_factor_noise:
    x: 0.01
    y: 0.01
    z: 0.01
  radius_prior_noise: 0.18
  radius_min: 0.15
  default_radius: 0.26
  radius_max: 0.5
  dz_prior_noise: 0.1
  default_dz: 0.0
  armor_observation_noise:
    tangential_error_m: 0.08
    radial_error_m: 0.018
    height_error_m: 0.05
    yaw_error_rad: 0.02
  radius_divergence:
    enable: true
    monitor_window_sec: 0.8
    min_peak_to_peak_m: 0.03
    min_direction_flip_count: 4

planner_conf:
  dt_sec: 0.005
  fail_polling_interval_sec: 0.1
  trajectory_half_horizon: 100
  rk45_yaw0: true
  iterative_yaw0: true
  rk45_traj: false
  iterative_traj: false
  shoot_offset: 0
  yaw_offset: 0.0
  pitch_offset: 0.0
  fire_thresh: 0.005
  max_yaw_acc: 50.0
  Q_yaw: [9e6, 0]
  R_yaw: 1
  max_pitch_acc: 100.0
  Q_pitch: [9e6,0]
  R_pitch: 1
  max_bullet_speed: 25.0
  default_bullet_speed: 22.0
  min_bullet_speed: 10.0
  trajectory_conf:
    ballistic_conf:
      g: 9.8
      k: 0.019
      barrel_length: 0.107
      time_step: 0.001
      max_fly_time: 0.8
      max_pitch_iterate_count: 80
      min_pitch_error_m: 0.01
      gimbal_pitch_max_degree: 30.0
      gimbal_pitch_min_degree: -10.0
    max_aim_iterate_count: 100
    max_aim_switch_armor_count: 10
    aim_ok_error_m: 0.02
    armor_front_facing_min_dot_product: 0.0
    armor_switch_distance_hysteresis_m: 0.03
