log_level: Info
robot_conf:
  r1: 0.26
  r2: 0.26
  dz: 0.1
  armor_type: Three
  armor_color: Blue
  drag_linear_acceleration: 8.0
  drag_angular_acceleration: 8.0
  power_linear_acceleration: 10.0
  power_angular_acceleration: 10.0
  time_step_ms: 17
  facing_armor_cos_incidence: 0.25
  hidden_invisible_armors: true
  camera_pos: [0.,0.]
  pub_conf:
    service_instance_event: [armors, fake_ap, data]
    frame_id: odom
