target("fake_ap")
set_kind("binary")
add_includedirs("fake_armors_publisher/include")
add_files("fake_armors_publisher/src/*.cpp")
add_packages("eigen")
add_packages("yaml-cpp")
add_packages("reflect-cpp")
add_packages("cxxopts")
add_packages("quill")
add_packages("ftxui")
-- NOTE: 这个是用来捕获键盘输入的，termios啥的玩不明白
add_deps("common_defs")
add_deps("tools")
add_rules("iceoryx_deps")
target_end()
