target("buff_detector")
set_kind("binary")
add_includedirs("buff_detector/include")
add_files("buff_detector/src/*.cpp")
add_packages("eigen")
add_packages("opencv")
add_packages("yaml-cpp")
add_packages("reflect-cpp")
add_packages("cxxopts")
-- add_packages("ceres")
add_packages("quill")
add_deps("common_defs")
add_deps("tools")
add_rules("iceoryx_deps")
add_rules("openvino_deps")
add_rules("gtsam_deps")
target_end()
