target("messages")
-- set_kind("headonly")
set_kind("static")
-- add_headerfiles("msgs/*.hpp")
add_includedirs("include", { public = true })
add_files("src/*.cpp")
add_rules("iceoryx_deps")
add_packages("opencv")
target_end()
