log_level: Debug
coord_conf:
  frame_size: 1.0
  frame_ids: ["map", "odom", "camera"] 
  static_frame_id: "map"
  tf_query_time_tolerance_ms: 1
  draw_frame_trajectory: true
  trajectory_frame_id: "odom"
  draw_camera_visualization: false
  camera_frame_id: "camera"
  camera_name: "camera0"
