log_level: Info
coord_conf:
  frame_size: 1.0
  frame_ids: ["map", "imu"] 
  static_frame_id: "map"
  tf_query_time_tolerance_ms: 1
  draw_frame_trajectory: true
  trajectory_frame_id: "imu"
  draw_camera_visualization: false
  camera_name: "camera0"
  camera_frame_id: "camera"
