rule("hik_deps")
on_load(function(target)
	target:add("includedirs", "third_party/hik_camera_sdk/include")
	if is_arch("x86_64") then
		target:add("linkdirs", "third_party/hik_camera_sdk/lib/amd64")
	else
		target:add("linkdirs", "third_party/hik_camera_sdk/lib/arm64")
	end
	target:add("links", "MvCameraControl")
end)
rule_end()

target("messages")
-- set_kind("headonly")
set_kind("static")
-- add_headerfiles("msgs/*.hpp")
add_includedirs("tools/include", { public = true })
add_files("msgs/*.cpp")
add_rules("iceoryx_deps")
add_packages("opencv")
target_end()

target("tools")
set_kind("static")
add_files("tools/src/*.cpp")
add_includedirs("tools/include", { public = true })
add_packages("opencv")
add_packages("eigen")
add_packages("yaml-cpp")
add_packages("nameof")
target_end()

includes("auto_aim")
includes("auto_buff")
includes("hardware_interface")
