target("libmessages")
-- set_kind("headonly")
set_kind("static")
-- add_headerfiles("msgs/*.hpp")
add_includedirs("tools/include/*.hpp", { public = true })
add_files("msgs/*.cpp")
add_rules("iceoryx_deps")
add_packages("opencv")
target_end()

target("libtools")
set_kind("static")
add_files("tools/src/*.cpp")
add_includedirs("tools/include/*.hpp", { public = true })
add_packages("opencv")
add_packages("eigen")
target_end()

includes("auto_aim")
includes("auto_buff")
