target("basic_tools")
set_kind("static")
add_includedirs("basic/include", { public = true })
add_files("basic/src/*.cpp")
add_packages("opencv")
add_packages("eigen")
add_packages("yaml-cpp")
add_packages("nameof")
add_deps("messages")
target_end()

target("math_tools")
set_kind("static")
add_includedirs("math/include", { public = true })
add_files("math/src/*.cpp")
add_packages("opencv")
add_packages("eigen")
add_packages("yaml-cpp")
add_deps("basic_tools")
add_packages("yaml_cpp_struct")
add_packages("fmt")
target_end()

-- target("visualization_tools")
-- set_kind("binary")
-- add_includedirs("visualization/include", { public = true })
-- add_files("visualization/src/*.cpp")
-- add_rules("iceoryx_deps")
-- add_packages("glfw")
-- add_packages("open3d_deps")
-- add_packages("eigen")
-- add_packages("opencv")
-- add_deps("messages")
-- target_end()
