-- target("basic_tools")
-- set_kind("static")
-- add_includedirs("basic/include", { public = true })
-- add_files("basic/src/*.cpp")
-- add_packages("opencv")
-- add_packages("eigen")
-- add_packages("yaml-cpp")
-- add_deps("messages")
-- add_packages("fmt")
-- add_packages("nameof")
-- add_packages("quill")
-- target_end()
--
-- target("math_tools")
-- set_kind("static")
-- add_includedirs("math/include", { public = true })
-- add_files("math/src/*.cpp")
-- add_packages("opencv")
-- add_packages("eigen")
-- add_packages("yaml-cpp")
-- add_deps("basic_tools")
-- add_packages("fmt")
-- add_packages("reflect-cpp")
-- target_end()
--
-- target("transform_tools")
-- set_kind("static")
-- add_includedirs("transform/include", { public = true })
-- add_files("transform/src/*.cpp")
-- add_packages("opencv")
-- add_packages("eigen")
-- add_packages("yaml-cpp")
-- add_deps("basic_tools")
-- add_packages("fmt")
-- add_packages("reflect-cpp")
-- add_deps("fast_tf")
-- add_rules("iceoryx_deps")
-- add_deps("messages")
-- add_packages("quill")
-- target_end()

target("tools")
set_kind("static")
add_includedirs(".", { public = true })
add_files("src/*.cpp")
add_packages("opencv")
add_packages("eigen")
add_packages("yaml-cpp")
add_deps("common_defs")
add_packages("fmt")
add_packages("nameof")
add_packages("quill")
add_deps("fast_tf")
add_packages("reflect-cpp")
add_rules("iceoryx_deps")
target_end()
